### PR TITLE
[Akshit] Adds UI support in config

### PR DESCRIPTION
**Pull request by ashu1994**

### CODE REVIEW

**Comment by oriff** [comment]
Hi, This is very useful for my use case.
Can somebody please review this? @tas50

**Comment by josephholsten** [comment]
@ashu1994 can you document how to test this? I'd love to verify that this is usable, but I don't know what I'm doing ;-)

**Comment by thorhs** [comment]
@josephholsten: If you set the ui attribute to true the vault.json file will include a config option for enabling the UI.  For testing the UI you open a web browser to https://<vault_addr>/ui, and you should see a login dialog.  That is all that needs to be tested with enabling the UI.

**Comment by PowerSchill** [comment]
This functionality was implemented with #115.

**Pull request closed without merging**
