### PR TITLE
Vault agent support

### PR DESCRIPTION
**Pull request by codayblue**
# Description

This PR has everything needed to configure and install vault agents

## Issues Resolved

- #144 

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by codayblue** [comment]
I see I did forget tests. I only checked the chefspec directory. Please hold. I will add tests.

**Comment by codayblue** [comment]
New commit to PR has tests now.

**Comment by mengesb** [comment]
Looked over this - appears to be fairly complete. thanks for the contribution! Hopefully others agree.

**Pull request merged**
